<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderProductService.Domain\OrderProductService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="throw" />
  </ItemGroup>

</Project>
