<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderProductService.Domain\OrderProductService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Ardalis.SmartEnum" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="throw" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Order\" />
  </ItemGroup>

</Project>
